version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - 543:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=project_database
  app:
    container_name: projeto-final-node-back
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
